config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources:accounts do 
      resources :transactions
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'sessions#new'
  post '/approve', to: 'transactions#approve'
  get   '/unauthorize', to: 'unauthorizes#new'
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    has_many :transactions
    validates :accname,  presence: true, length: { maximum: 50 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :account
    has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif",'application/pdf']
    validates :amount, :numericality => { :only_integer => true}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :accounts, dependent: :destroy
    before_save {self.emailId = emailId.downcase}
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :emailId, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }   
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 } 
end

app/controllers/accounts_controller.rb
# class for handling acocunt name of users
# frozen_string_literal: true.
class AccountsController < ApplicationController
  before_action :authenticate_user
  def index
    @var = current_user.admin
      if @var
        @accounts = Account.all
      else
        @accounts = current_user.accounts.all
      end
    @consumer = current_user
  end
  
  def new
    @account = Account.new
  end
    
  def create
    @account = current_user.accounts.create(account_params)
    if @account.save
      # do nothing 
    else
      flash[:notice] = 'Account Name Error'
    end
    redirect_to current_user
  end

  def show
    @account = current_user.accounts.find(params[:user_id])
  end

  def edit
    @account = current_user.accounts.find(params[:id])
  end

  def update
    @account = current_user.accounts.find(params[:id])
    if @account.update(account_params)
      redirect_to user_accounts_path(current_user)
      flash[:success] = "Document Updated"
    else
      render 'edit'
    end
  end
 
  def destroy
    @account = current_user.accounts.find(params[:id])
    if @account.destroy
      redirect_to user_accounts_path(current_user)
      flash[:success] = 'Document has been deleted'
    else
      flash[:notice]  = 'Document cannot be deleted'
    end
  end

  private

  def account_params
    params.require(:account).permit(:accname)
  end
end

app/controllers/application_controller.rb
# class for including application level instructions
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# Session Class for handling Sessions after login of user
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :already_login, except: :destroy
  
  def new

  end

  def create
    user = User.find_by(emailId: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user_accounts_path(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
  
  def show
  
  end
end

app/controllers/transactions_controller.rb
# class for handling transactions of user
# frozen_string_literal: true

class TransactionsController < ApplicationController

  before_action :authenticate_user, except: :approve
  def index
    @transactions = Transaction.all
    @account = Account.find(params[:account_id])
    @admin = current_user.admin
    @transact = @account.transactions
  end
    
  def new
    @transaction = Transaction.new
  end

  def create
    @account = Account.find(params[:account_id])
    @transaction = @account.transactions.create(transaction_params)
    if @transaction.save
      redirect_to user_account_transactions_path
    else
      render 'new'
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end
  
  def update
    @account = Account.find(params[:account_id])
    @transaction = @account.transactions.find(params[:id])
    if @transaction.update_attributes(transaction_params)
      flash[:success] = "Document Updated"
      redirect_to user_account_transactions_path
    else
      render 'edit'
    end
  end

  def show
    # Not of work
  end

  def approve
    @account = Account.find(params[:account_id])
    @transaction = Transaction.find(params[:transaction_id])
    if params[:approved] == 'yes'
      @transaction.approve = true
      flash[:success] = "Transaction Approved"
    else
      @transaction.approve = false
      flash[:success] = "Transaction Disapproved"
    end
    @transaction.save
    redirect_to user_account_transactions_path(current_user, @account)
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :description, :image)
  end
end

app/controllers/unauthorizes_controller.rb
# class to redirect in case of URL change by user
# frozen_string_literal: true

class UnauthorizesController < ApplicationController
  def new
    # just for redirection
  end  
  
  def index
    # just for redirection
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
# Users class for creating new users

class UsersController < ApplicationController
  before_action :already_login
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_accounts_path(@user)
    else
      render 'new'
    end
  end

  private

  def user_params
       params.require(:user).permit(:name, :emailId, :password, :password_confirmation, :admin)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        
    end
    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
            !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def authenticate_user
        # var = params[:user_id].to_i
        if session[:user_id] != params[:user_id].to_i
            redirect_to unauthorize_path
        end
    end

    def already_login
        if logged_in?
            redirect_to login_path
        end
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/unauthorizes_helper.rb
module UnauthorizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/edit.html.erb
<html>
<body>
<h1 align="center"><Strong>Edit Account Name</Strong></h1>
<div class = "container">
<%= form_for(:account, url:user_account_path, method: :PATCH) do |f| %>
<div class = "row">
    <div class = "col"><Strong>Current Account Name is:  </Strong><%= @account.accname %></div>
</div>
<br>
    <div class = "row">
    <div class = "col"><Strong>Enter New account Name or Click on delete:</Strong></div>
</div>
<div class="row">
    <div class = "col-sm-5"><Strong><p><%=f.text_field :accname, class:'form-control' %></p></Strong></div>
</div>
<div class="row">
    <div class="col-sm-1"><%= f.submit "Update", class:'btn btn-primary'%></div>
</div>
<br>
<% end %>
<%= form_for(:account, url:user_account_path, method: :DELETE) do |f| %>
<div class="row">
    <div class="col"><%= f.submit "Delete", class:'btn btn-primary'%></div>
</div>
<% end %>
<div class="row">
    <div class = "col-sm-5"><Strong><p><%= link_to "Back", user_accounts_path %></p></Strong></div>
</div>
</div>
</body>
</html>

app/views/accounts/index.html.erb
<!DOCTYPE html>
  <body>
  <div class = "container">
      <h1 align="center"><Strong>Transaction System</Strong></h1>
      <div class = "row">
            <div class = "col-sm-10"><p align="right">Name : <%= current_user.name%></p></div>
            <div class = "col-sm-2"><%=link_to "Log out", logout_path, method: :delete%></p></div>
      </div>
      <%= form_for(:account, url:user_accounts_path([@current_user]), method: :POST) do |f| %>
            <%= render 'shared/error_messages_account' %>
      <div class="row">
            <div class = "col-sm-5"><p align="left"><p><Strong>Enter account name to create new account:</Strong></p></div>
      </div>
      <div class="row">
            <div class = "col-sm-5"><p align="left"><%=f.text_field :accname, class:'form-control' %></p></div>    
      </div>
      <div class="row">
            <div class = "col-sm-5"><p align="left"><%= f.submit "Create", class:"btn btn-primary"%></div>    
      </div>
      <% end %>
      <div class = "row">
            <div class = "col-sm-10"><Strong><p align="left">Account Names List</p></Strong></div>
      </div>
      <% if @accounts.empty? %>
            <div class = "row">
                  <div class = "col">No Acounts Now</div>
            </div>
      <% else %>
      <% @accounts.each do |account| %>
            <div class = "row">
                  <div class = "col"><%= account.accname %></div>
                  <div class = "col"><%= link_to "Edit", edit_user_account_path(@current_user, account)%></div>
                  <div class = "col"><%= link_to "Transactions" , user_account_transactions_path(@current_user, account)%></div>
            </div> 
      <% end %>
      <% end %>
</div>
  </body
</html>

app/views/accounts/new.html.erb
<html>
<title>

</title>
<head>
</head>

<body>

This is new Page fior Accounts
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashExpenseManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_account.html.erb
<% if current_user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(current_user.errors.count, "error") %>.
    </div>
    <ul>
    <% current_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<html>
<body>
<h1 align="center"><Strong>Update File</Strong></h1>
<div class = "container">
<%= form_for(:transaction, url: user_account_transaction_path, method: :PATCH) do |f| %>
    <div class="row">
        <div class = "col-sm-5">Enter Amount</div>
    </div>
    <div class="row">
        <div class = "col-sm-5"><p><%=f.text_field :amount, class:'form-control' %></p></div>
    </div>
    <div class="row">
        <div class = "col-sm-5">Enter Description</div>
    </div>
    <div class="row">
        <div class = "col-sm-5"><p><%= f.text_field :description, class:'form-control' %></p></div>
    </div>
    <div class="row">
        <div class = "col-sm-5">Upload Attachment</div>
    </div>
    <div class="row">
        <div class = "col-sm-5"><p><%= f.file_field :image, class:'form-control'%></p></div>
    </div>
    <div class="row">
        <div class = "col-sm-5"><p align="left"><%=f.submit "Update", class:"btn btn-primary"%></div>    
    </div>
    <% end %>
</div>
</body>
</html>

app/views/transactions/index.html.erb
<html>
<title>
</title>
<head>  
<Strong></Strong>
</head>
<body>
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-10"><p align="right">Name:  <%= current_user.name %></p></div>
        <div class="col-sm-2"><p align="left"><%= link_to "Log out" ,logout_path, method: :delete %></p></div>
    </div>
</div>
<h1 align="center">
<Strong>List of Transactions</Strong>
</h1><br>
<div class="container">
<div class="row">
    <div class ="col-sm-1"><Strong>Amount</Strong></div>
    <div class ="col-sm-3"><Strong>Description</Strong></div>
    <div class ="col-sm-2"><Strong>Document Link</Strong></div>
    <div class ="col-sm-3"><Strong>Update_link</Strong></div>
    <% if current_user.admin %>
        <div class ="col-sm-3"><Strong>Document Approve(Click to Approve)</Strong></div>   
    <% else %>
        <div class ="col-sm-2"><Strong>Approval Status</Strong></div>   
    <% end %>
    
</div>
<br>
<% @transact.each do |trans| %>
    <div class = "row">
          <div class = "col-sm-1"><%= trans.amount %></div>
          <div class = "col-sm-3"><%= trans.description %></div>
          <div class = "col-sm-2"><%= link_to "transaction_document" , trans.image.url %></div>
          
            <%if current_user.admin %>
              <div class = "col-sm-3"><Strong>Admin Cannot Edit</Strong></div>
            <% else %>
                <% if trans.approve %>
                <div class = "col-sm-3"><Strong>Cant Edit Anymore</Strong></div>
                <% else %>
                <div class = "col-sm-3"><%= link_to "delete_image/update_image", edit_user_account_transaction_path(@current_user,@account,trans)%></div>
            <%end%> 
          <% end %>
             <% if current_user.admin %>
                <% if trans.approve %>
                    <div class = "col-sm-3"><%= link_to "Disapprove?(Already Approved)", approve_path(:transaction_id => trans.id, :approved => 'no', :account_id => params[:account_id] ), method: :POST %></div>
                <%else%>
                    <div class = "col-sm-3"><%= link_to "Approve", approve_path(:transaction_id => trans.id, :approved => 'yes', :account_id => params[:account_id]), method: :POST %></div>
                <%end%>
          <% else %>
                <% if trans.approve %>
                    <div class = "col-sm-3"><Strong>Approved</Strong></div>
                <% else %>
                    <div class = "col-sm-3"><Strong>Not Approved</Strong></div>
                <% end %>
          <% end %>
          <div class = "row"><p><br></p></div>
    </div>            
<% end %>
</div>
<br>
<h1 align="center">
<Strong>Create New Transaction</Strong>
</h1>
<div class="container">

<%= form_for(:transaction, url: user_account_transactions_path([@current_user, @account]), method: :POST) do |f| %>
    <div class="row">
        <div class = "col-sm-5">Enter Amount</div>
    </div>
    <div class="row">
        <div class = "col-sm-5"><p><%=f.text_field :amount, class:'form-control' %></p></div>
    </div>
    <div class="row">
        <div class = "col-sm-5">Enter Description</div>
    </div>
    <div class="row">
        <div class = "col-sm-5"><p><%= f.text_field :description, class:'form-control' %></p></div>
    </div>
    <div class="row">
        <div class = "col-sm-5">Upload Attachment</div>
    </div>
    <div class="row">
        <div class = "col-sm-5"><p><%= f.file_field :image, class:'form-control'%></p></div>
    </div>
    <div class="row">
        <div class = "col-sm-5"><p align="left"><%=f.submit "Create", class:"btn btn-primary"%></div>    
    </div>
    <% end %>
</div>
</body> 
</html>

app/views/transactions/new.html.erb
<html>
<title>
</title>
<head>  
<Strong>Error Messages </Strong>
</head>
<body>
Invalid Parameters of Text Box
</body> 
</html>

app/views/transactions/show.html.erb
<html>
<body>
Document Updated
</body>
</html>

app/views/unauthorizes/index.html.erb
<h1>
Unauthorized Access
</h1>

app/views/unauthorizes/new.html.erb
<h1>
Unauthorized Access
</h1>

app/views/users/index.html.erb
<div class="container" style="background-color:grey" align="center">
<div class="row">
<%= form_with scope: :user, local: true do |form| %>
    <p>
        <%=form.label :Email%><br>
        <%=form.text_field :Email%>
    </p>
    <p>
        <%=form.label :Password%><br>
        <%=form.text_field :Password%>
    </p>
    <p>
        <%= form.submit "Log in", class: "btn btn-primary" %>
    </p>
    <p>
        <%= link_to 'New User', new_user_path %>
    </p>
<%end%>
</div>
</div>

app/views/users/new.html.erb
<html>
<div class = "container">
<div class = "row">
<div class="col-md-6 col-md-offset-3">
<%= form_with scope: :user, url: users_path(:id), method: :POST, local: true do |form| %>
    <%= render 'shared/error_messages' %>
    <Strong >Create your Account</Strong>
    <p>
        <br>
        <%=form.label :Name%><br>
        <%=form.text_field :name, class:'form-control'%>
    </p>
    <p>
        <%=form.label :Email%><br>
        <%=form.text_field :emailId, class:'form-control'%>
    </p>
    <p>
        <%=form.label :password%><br>
        <%=form.password_field :password, class:'form-control'%>
    </p>
    <p>
        <%=form.label :"Confirm Password"%><br>
        <%=form.password_field :password_confirmation, class:'form-control'%>
    </p>
    <p>
        <%= form.radio_button :admin, class:'form-control'%>  Is Admin?
    </p>
    <p>
        <%= form.submit "Create new account", class: "btn btn-primary" %>
    </p>
<%end%>
</div>
</div>
</div>
</html>